name: Lint & Test

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com
    - uses: actions/cache@v2
      id: cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-packages-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-npm-packages
    - name: Install dependencies
      run: npm ci
    - run: npm run lint
    - run: npm test
